#!/Users/rsm38/.nvm/versions/node/v8.11.1/bin/node

let request = require("request");
let Phrase = require("raysmith745-palindrome");
let url = 'https://cdn.learnenough.com/phrases.txt'

request(url, function (error, response, body) {
    body.split("\n").forEach(function(line) {
        phrase = new Phrase(line);
        if (phrase.palindrome()) {
            console.log("palindrome detected:", line);
        }
    });
});
