#!/Users/rsm38/.nvm/versions/node/v8.11.1/bin/node

let fs = require("fs");
let Phrase = require("raysmith745-palindrome");

let text = fs.readFileSync("phrases.txt", "utf8");
text.split("\n").forEach(function(line) {
    let phrase = new Phrase(line);
    if (phrase.palindrome()) {
        console.log("palindrome detected:", line);
    }
});